### ISSUE TITLE
Exception: Error running pod install

### ISSUE THREAD

**Issue by mohammednabil95** [SachinBhankhar/flutter_restart_plugin#1]
After installing this plugin and run the app in iOS device then it is showing an error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by joymyr** [comment]
And when running pod install I get 
```
No podspec found for `flutter_app_restart` in `.symlinks/plugins/flutter_app_restart/ios
```

Seems like iOS is not supported after all

**Comment by joymyr** [comment]
Now I see that this is a fork from flutter_restart for null safety, and the original project seems to be dead. Unfortunately the renaming is messed up, and this fork seems to be dead as well.

**Comment by SachinBhankhar** [comment]
I'm not the original maintainer of this package. Please fork the package to update
