### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by SloppyCodes** [SachinBhankhar/flutter_restart_plugin#5]
I'm getting the following error when trying to run my app:
`.pub-cache\hosted\pub.dartlang.org\flutter_app_restart-1.0.0\android\src\main\kotlin\com\example\flutter_app_restart\FlutterRestartPlugin.kt: (55, 18): Type mismatch: inferred type is Activity? but Activity was expected`

**Comment by phackwer** [comment]
Same here

.pub-cache/hosted/pub.dartlang.org/flutter_app_restart-1.0.0/android/src/main/kotlin/com/example/flutter_app_restart/FlutterRestartPlugin.kt: (55, 18): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_app_restart:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleDebug'...                              4.7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Milimeter** [comment]
Having the same issue. Was this solved?

**Comment by marcoedomingos** [comment]
I was able to solve this issue, his change this in your pubspec for the fixed lib.
`flutter_app_restart:`
`    git:`
`      url: git://github.com/Marco4763/flutter_restart_plugin.git`
`      ref: fix/issue_5`
